openapi: 3.0.3
info:
  title: AlimentosAPI
  version: v1.0
  description: Api para administrar elimentos
  termsOfService: 'http://terms-of-service.com'
  contact:
    email: edwin.romero@scotiabank.com.co
    name: edwin romero
    url: 'https://www.linkedin.com/rcabezas1'
  license:
    name: GNU GPL
    url: 'https://license.com'
servers:
  - url: https://{environment}:{port}/alimentos
    variables:
      environment:
        default: api    # Production server
        enum:
          - api         # Production server
          - api.dev     # Development server
          - api.uat # Staging server
          - localhost   # Local server
      port:
        default: '8080'    # Production server
        enum:
          - '8080' # Production server
          - '8098' # Development server
          - '8081' # Staging server
tags:
  - name: Frutas
    description: Operaciones con las frutas
  - name: Peras
paths:
  /fruta/pera:
    post:
      tags:
        - Frutas
      summary: crear una pera
      description: Metodo para crear peras
      operationId: crearPera
      requestBody:
        description: Elementos necesarios para la creación de una pera
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeraRequest'
            example: 
              data: 
                tipo: Verde
                nombre: Pera Arrallanas
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example: 
                data:
                  id: 123
                  tipo: Verde
                  nombre: Pera Arrallana
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              examples:
                nombReq:
                  summary: Nombre requerido
                  value:
                    errores: 
                    - codigo: 'REQ'
                      valor: 'nombre requerido'
                tipoReq:
                  summary: Tipo requerido
                  value:
                    errores: 
                    - codigo: 'REQ'
                      valor: 'tipo requerido'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example:
                errores: 
                  - codigo: 'ERR'
                    valor: 'Sistema no disponible'
        '502':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example:
                errores: 
                  - codigo: 'ERR2'
                    valor: 'Sistema no disponible'
    get:
      tags:
        - Frutas
      description: Obtener las peras que están disponibles
      operationId: getPera
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeraResponse'
                example:
                  - data:
                      id: 123
                      tipo: Verde
                      nombre: Pera Arrallana
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeraResponse'
                example:
                  - errores:
                      - codigo: NF
                        valor: No encontramos datos
    put:
      tags:
        - Frutas
      summary: actualizar una pera
      description: Metodo para actualizar peras
      operationId: actualizarPera
      requestBody:
        description: Elementos necesarios para la actualizacion de una pera
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeraUpdateRequest'
            example:
              data:
                tipo: Cafe
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example: 
                data:
                  nombre: Pera arrallana
                  id: 123
                  tipo: Verde
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example:
                errores: 
                  - codigo: 'REQ'
                    valor: 'nombre requerido'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example:
                errores: 
                  - codigo: 'ERR'
                    valor: 'Sistema no disponible'
  /fruta/{id}:
    get:
      summary: Obtiene la pera por id
      description: Obtiene la pera por id unico
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Id de la pera a obtener
      tags:
        - Frutas
      operationId: getPeraPorId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeraResponse'
              example: 
                data:
                  id: 123
                  tipo: Verde
                  nombre: Pera Arrallana
    delete:
      description: Eliminar la pera mediante la busqueda del id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Id de la pera a eliminar
      tags:
        - Frutas
      operationId: deletePeraPorId
      responses:
        '204':
          description: No content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeraResponse'
                example:
                  - errores:
                      - codigo: NF
                        valor: No encontramos datos
components:
  schemas:
    PeraRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            nombre:
              type: string
            tipo:
              type: string
              enum:
              - Verde
              - Cafe
              - Organica
    PeraUpdateRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            tipo:
              type: string
              enum:
              - Verde
              - Cafe
              - Organica
    PeraResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            nombre:
              type: string
            id:
              type: integer
              minimum: 1
            tipo:
              type: string
              enum:
              - Verde
              - Cafe
              - Organica
        errores:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        codigo:
          type: string
        valor:
          type: string